// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bthbrfmtzvpedsozvvtc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ0aGJyZm10enZwZWRzb3p2dnRjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3MTg4MTAsImV4cCI6MjA2NTI5NDgxMH0.XtdKYbJoRuJ4teYa2IVYPLJq58E0Dp3jokqhWtNvrNA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);